# Generated by Django 5.2.17 on 2026-08-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="avatar/default_avatar.jpg",
                upload_to="avatar",
                verbose_name="头像",
            ),
        ),
    ]
