# Generated by Django 5.2.17 on 2026-08-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_auth", "0002_alter_myuser_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="is_superuser",
            field=models.BooleanField(default=False, verbose_name="是否超级用户"),
        ),
    ]
