# Generated by Django 5.2.17 on 2026-08-31 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="content",
            new_name="comment",
        ),
    ]
